name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t murtuzakteqbit/sample-demo-app:${{ github.sha }} .
          docker push murtuzakteqbit/sample-demo-app:${{ github.sha }}

      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: murtuzak-teqbit/demo-app-helm
          ref: main # Specify the branch where the Helm chart is stored

      - name: Update Helm Chart Image Tag
        run: |
          git pull origin main
          sed -i "s/tag: \"v2\"/tag: \"v2-${GITHUB_SHA:0:7}\"/" charts/demo-app-helm/values.yaml # Replace path/to/values.yaml with the actual path
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Commit Changes
        run: |
          git config --global user.name 'murtuzak-teqbit'
          git config --global user.email 'murtuzak@teqbit.com'
          git add .
          git commit -m "Update image tag to include GitHub SHA"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true


