name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   # with:
      #   #   username: ${{ secrets.DOCKER_USERNAME }}
      #   #   password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t murtuzakteqbit/sample-demo-app:${{ github.sha }} .
          docker push murtuzakteqbit/sample-demo-app:${{ github.sha }}

      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/murtuzak-teqbit/demo-app-helm
          ref: main # Specify the branch where the Helm chart is stored

      - name: Update Helm Chart Image Tag
        run: |
          sed -i "s/tag: \"v2\"/tag: \"v2-${GITHUB_SHA:0:7}\"/" charts/demo-app-helm/values.yaml # Replace path/to/values.yaml with the actual path
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update image tag to include GitHub SHA"
          git push origin main # Replace <branch-name> with the branch where you want to push changes


