name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_deploy_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t murtuzakteqbit/sample-demo-app:dev-${{ github.sha }} .
          docker push murtuzakteqbit/sample-demo-app:dev-${{ github.sha }}

      - name: Checkout helm3 repository
        uses: actions/checkout@v3
        with:
          repository: murtuzak-teqbit/demo-app-helm
          ref: dev
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Update Helm Chart Values
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: charts/demo-app-helm/dev.yaml
          tag_value: dev-${{ github.sha }}
          commit_branch: dev

  build_and_deploy_staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t murtuzakteqbit/sample-demo-app:staging-${{ github.sha }} .
          docker push murtuzakteqbit/sample-demo-app:staging-${{ github.sha }}

      - name: Checkout helm3 repository
        uses: actions/checkout@v3
        with:
          repository: murtuzak-teqbit/demo-app-helm
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Update Helm Chart Values
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: charts/demo-app-helm/staging.yaml
          tag_value: main-${{ github.sha }}
          commit_branch: main